install:
  - npm install

before_script:
  - npm install -g webpack webpack-cli bower
  - bower install
script:
  - webpack

deploy:
  provider: heroku
  api_key:
    secure: $HerokuApiKey
  app: my-example-react-app