before_install:
  - npm install -g bower
install:
  - npm install
  - bower install

before_script:
  - npm install -g webpack webpack-cli
script:
  - webpack

deploy:
  provider: heroku
  api_key:
    secure: $HerokuApiKey
  app: my-example-react-app